Adds yarn as a devdep, fixes #182; commits yarn.lock, fixes #183; commits package-lock.json, fixes #184
shikijs/shiki pull request #185
Opened 2021-08-01 04:43 UTC by StoneCypher

This PR does three things.

1. This adds `yarn` as a developer dependency, because `lerna` runs it on `npm run build`.  Adding this fixes #182 
2. This commits `package-lock.json`, fixing #184 
3. This commits `yarn.lock`, fixing #183

2021-08-01 05:07 UTC, StoneCypher commented
fixes @StoneCypher/fsl#612

2021-08-01 05:53 UTC, antfu commented
Let's do one thing at a time, I can revert the changes for 2. 3. 4.?

2021-08-01 06:55 UTC, StoneCypher commented
you can if you want, but your downstream users can't use the build because you're requiring global installs of tools that aren't in your build file, and having the locks in the repo is an absolute requirement for them to function correctly

2021-08-03 16:52 UTC, StoneCypher commented
@antfu - I don't know how to set up a CI build here.  The original PR built, but the current one doesn't, for lack of yarn

What am I doing wrong please?

2021-08-03 18:33 UTC, orta requested changes

2021-08-03 18:33 UTC, orta commented on package.json
> -  "dependencies": {},
Can you undo this and the removal of the yarn.lock please

2021-08-03 20:36 UTC, StoneCypher commented on package.json
> -  "dependencies": {},
> Can you undo this

NPM did this, but okay

2021-08-03 20:48 UTC, StoneCypher commented on package.json
> -  "dependencies": {},
done

2021-08-04 06:34 UTC, merged

2021-08-04 06:34 UTC, orta commented
Thanks!

2021-08-14 04:46 UTC, octref commented on docs/languages.md
> +- Add your language to the language list, below
This is automatic with the script. I'm removing this on main branch.

2021-08-14 05:00 UTC, StoneCypher commented on docs/languages.md
> +- Add your language to the language list, below
It didn't happen for me, but okay

2021-08-14 05:09 UTC, octref commented on docs/languages.md
> +- Add your language to the language list, below
https://github.com/shikijs/shiki/blob/ff2b606a55eb2c666719e834a3f72db4ba128e7b/scripts/grammars/updateGrammarSourceFiles.ts#L109-L113

Not sure what went wrong for you though 🤷‍♂️

2021-08-14 05:11 UTC, StoneCypher commented
I tried to fix it but I was asked not to

On Fri, Aug 13, 2021, 10:09 PM Pine ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In docs/languages.md
> <https://github.com/shikijs/shiki/pull/185#discussion_r688865272>:
>
> > @@ -16,6 +16,7 @@ A [build script](/scripts/pullGrammars.sh) runs every day to pull latest grammar
>
>    - Less than 100 columns if possible
>
>    - Link to source in the last line, for example `# From https://poignant.guide/book/chapter-5.html` <https://poignant.guide/book/chapter-5.html>
>
>  - Run `yarn update:grammars`
>
> +- Add your language to the language list, below
>
>
>
> https://github.com/shikijs/shiki/blob/ff2b606a55eb2c666719e834a3f72db4ba128e7b/scripts/grammars/updateGrammarSourceFiles.ts#L109-L113
>
> Not sure what went wrong for you though 🤷‍♂️
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/shikijs/shiki/pull/185#discussion_r688865272>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAAS5KT4OPZ5P65KDAQSG63T4X3BTANCNFSM5BKXAEUA>
> .
>

2021-08-14 05:39 UTC, StoneCypher commented on docs/languages.md
> +- Add your language to the language list, below
it's because the script assumes the presence of the yarn toolchain, which i don't have, so the script fails

it can be fixed by putting yarn into your developer dependencies, so that when a standard node user installs the project, all of the tooling is present