Add optional preserveFontStyle
shikijs/shiki pull request #23
Opened 2019-11-29 21:44 UTC by mrinalini-m

In response to this feature requesst: https://github.com/octref/shiki/issues/15
Optional preserveFontStyle passed as a prop in 

```(js)
shiki
  .getHighlighter({
     theme: 'nord',
     preserveFontStyle: false
   })
```
I found the style maps from vscode-textmate but I didn't see a mapping function like colorMap. 
```(js)
 this._styleMap = {
    1: `font-style: italic;`, 
    2: `font-weight: bold`,
    4: `text-decoration: underline`
}
```

2020-03-24 15:48 UTC, h-2 commented
I would very much like to see this merged, thank you for creating this PR! Is there anything I can do to help get this in? I have just patched a local install, but my front-end (shiki-latex) doesn't automatically pick up the support...

2020-08-20 14:31 UTC, octref requested changes
Good work and sorry for leaving this stale for too long. I'll do the conflict resolution myself and fix some issues.

2020-08-20 14:31 UTC, octref commented on package.json
> +  "version": "0.1.7",
Let's not do that because it's a yarn workspace.

2020-08-20 14:31 UTC, octref commented on README.md
> +    preserveFontStyle: false //Optional. Defaults to true
I need to think a bit about adding this in the high level API. For now I'd just leave that in the `codeToHtml` options.

2021-03-18 03:40 UTC, octref commented
I merged via https://github.com/shikijs/shiki/commit/3b9583519a456efab3b040039594e0f459bad340
Thanks for your contribution.

2021-03-18 03:40 UTC, closed without merging