feat: dependency updates incl. textmate
shikijs/shiki pull request #377
Opened 2022-11-27 21:52 UTC by muenzpraeger

- [x] Add a test if possible
- [x] Format all commit messages with [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/)

- [x] This PR fixes #343, #361 

This PR updates all dependencies to recent versions (which actually also caused a few other changes). The change also included the update to the most recent `vscode-textmate` version.

2022-11-27 21:53 UTC, muenzpraeger commented on jest.config.js
> +    escapeString: true,
There was a change in Jest -> they don't escape anymore. For the sake of simplicity (no updated snapshots) in this PR I set the tests to use the previous behaviour.

2022-11-27 21:54 UTC, muenzpraeger commented on jest.config.js
> +    '^.+\\.tsx?$': [
Another Jest change, this needs now to be a part of the `transform` object.

2022-11-27 21:55 UTC, muenzpraeger commented on packages/renderer-svg/src/__tests__/styleAttributes.test.ts
> +  expect(out).not.toContain(`<svg viewBox="0 0 150 `)
The test was failing b/c of a wrong check. ;-)

2022-11-27 21:56 UTC, muenzpraeger commented on packages/shiki/src/stackElementMetadata.ts
> +        (_containsBalancedBracketsBit << MetadataConsts.BALANCED_BRACKETS_OFFSET) |
Only implemented, but not really exposed (yet).

2022-11-29 03:33 UTC, drwpow commented on packages/shiki/package.json
> +  "type": "module",
This will break the package because `dist/index.js` is still CommonJS. This should be removed unless the `main` import is also changed to `dist/index.esm.js`, or an [import map with conditional exports](https://nodejs.org/api/packages.html#conditional-exports) is also added (which IMO is a breaking change and should be its own PR)

2022-11-29 03:33 UTC, drwpow commented on packages/shiki/package.json
>      "vscode-oniguruma": "^1.6.1",
This can be bumped as well

2022-11-29 03:35 UTC, drwpow commented
This PR would help the error I’m currently encountering (Node 18, macOS 13.x, Apple silicon chip):

```
import object field 'setTempRet0' is not a Function
```

Bumping `vscode-oniguruma` and `vscode-textmate` to the most recent versions seems to fix that error.

2022-11-29 03:50 UTC, Gerrit0 commented on packages/shiki/package.json
> +  "type": "module",
Yes, please don't do this. TypeDoc depends on Shiki, and I *really* don't want to deal with the pain that is ESM.

2022-11-29 03:52 UTC, Gerrit0 commented on packages/renderer-svg/src/__tests__/styleAttributes.test.ts
> +  expect(out).not.toContain(`<svg viewBox="0 0 150 `)
I'm not convinced the check was wrong... I think something updated in the renderer which resulted in an output change, but checking not contains is very suspicious...

2022-11-29 03:53 UTC, Gerrit0 requested changes

2022-11-29 03:53 UTC, Gerrit0 commented on packages/shiki/rollup.config.js
> +        targets: [{ src: resolve('node_modules/vscode-oniguruma/release/onig.wasm'), dest: 'dist' }]
Why?

2022-11-29 08:13 UTC, muenzpraeger commented on packages/renderer-svg/src/__tests__/styleAttributes.test.ts
> +  expect(out).not.toContain(`<svg viewBox="0 0 150 `)
I _think_ the change is correct. Here's why:

- The test description says it is a check that the render should _ignore_ the minimal background width.
- The [test passes](https://github.com/shikijs/shiki/blob/main/packages/renderer-svg/src/__tests__/styleAttributes.test.ts#L41) a value of 150 to `getSVGRenderer` for `bgMinWidth`. So that's what the SVG should have at minimum. And that's the value that should be ignore - according to the test description - if  the SVG width is higher.
- The renderer [validates via Math.max() the actual width against the min width](https://github.com/shikijs/shiki/blob/main/packages/renderer-svg/src/index.ts#L170-L173). In this test case the actual width is higher than the min width - so the actual width will be used instead of the min width.
- If the min width would be set on the SVG, then `<svg viewBox="0 0 150 ` would be correct. But as the actual width should override the min width the test should only pass when it's _not_ `<svg viewBox="0 0 150 `.

Happy to be proven wrong though, first time for me in that codebase. 🤷🏼‍♂️

2022-11-29 09:13 UTC, muenzpraeger commented on packages/shiki/rollup.config.js
> +        targets: [{ src: resolve('node_modules/vscode-oniguruma/release/onig.wasm'), dest: 'dist' }]
The usage of `require.resolve` [is throwing ](https://nodejs.org/docs/latest-v18.x/api/esm.html#esm_no_require_resolve) b/c of the module nature of Rollup.

The alternative option to get back `require.resolve` (and not to use `path.resolve`) would be to re-create require:

```javascript
import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);
```

I've no strong opinion on either of both approaches.

2022-11-29 09:45 UTC, muenzpraeger commented on packages/shiki/package.json
> +  "type": "module",
Good point, oversight on my end. Removed this, and instead renamed the rollup config files (which actually have been the driver for this).

2022-11-29 13:28 UTC, Gerrit0 commented on packages/renderer-svg/src/__tests__/styleAttributes.test.ts
> +  expect(out).not.toContain(`<svg viewBox="0 0 150 `)
Looks like you're correct, thanks! I missed the "not" in the test description

2022-11-29 13:30 UTC, muenzpraeger commented on packages/renderer-svg/src/__tests__/styleAttributes.test.ts
> +  expect(out).not.toContain(`<svg viewBox="0 0 150 `)
Been there too. ;-)

2022-11-29 13:31 UTC, Gerrit0 commented on packages/shiki/rollup.config.js
> +        targets: [{ src: resolve('node_modules/vscode-oniguruma/release/onig.wasm'), dest: 'dist' }]
Ah, makes sense! I didn't remember the module change when seeing this. This is probably fine, assuming hoisting doesn't change the actual file location

2022-12-02 10:50 UTC, orta commented on jest.config.js
> +    escapeString: true,
I made those changes in Jest ;) - but I dig not making things change unnecessarily

2022-12-02 10:51 UTC, orta commented
Yeah, I agree, this is a good PR 

I'll try commit some time this weekend to deploying a new shiki release 👍🏻

2022-12-02 11:05 UTC, muenzpraeger commented
@orta Cool! I'll have 2-3 more PRs in pipe (think of them as proposals, so not mandatory if you disagree). I'll try to get them in within the next 24h.

One of them is actually also adding more docs. ;-)

2022-12-16 09:55 UTC, muenzpraeger commented
With the latest commit we can eventually supersede #379 (added embedded language resolution to IGrammarConfiguration)

2022-12-18 16:36 UTC, orta commented
OK, that's  green now - biggest question mark on the PR is the removal of `IRawThemeSetting` to `any` but it doesn't seem to be user-facing so it's not a blocker IMO

Thanks for this @muenzpraeger - lets see if I can get all this wrangled into a release after I go through the other PRs.

2022-12-18 16:36 UTC, merged

2022-12-18 17:02 UTC, muenzpraeger commented
Also not a big fan of the `any` changes either, but I figured they don't have an impact on the implementation.

I've seen on the [vscode-textmate repo this issue](https://github.com/microsoft/vscode-textmate/issues/185) with no response yet, so potentially an oversight on their end.

2022-12-18 17:57 UTC, orta commented
NP, all these changes just got shipped in 0.12.0 - thanks!