feat: resolve embedded languages automatically
shikijs/shiki pull request #379
Opened 2022-12-01 23:14 UTC by muenzpraeger

- [x] Add a test if possible
- [x] Format all commit messages with [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/)

The current implementation hands off the ownership of understanding if and what embedded languages are needed to the document author.

```typescript
const highlighter = await getHighlighter({
  theme: 'nord',
  langs: ['html']
})
// Do we have JavaScript in that HTML? Ok, let's load it also.
await highlighter.loadLanguage('javascript');
// Do we have CSS in that HTML? Ok, let's load it also.
await highlighter.loadLanguage('css');
``` 

Now, this is a simple example. But there can be more complex ones, with multiple levels of embedded languages.

This PR ensures that every language that is embedded within another is auto-loaded, so that the implementers won't have to think about it.

The test shows the full example.

2022-12-02 04:10 UTC, Gerrit0 requested changes

2022-12-02 06:15 UTC, muenzpraeger commented on packages/shiki/src/__tests__/embeddedLanguages.test.ts
> +  console.log(languages)
🤦‍♂️

2022-12-02 10:49 UTC, orta commented
Looks like some recursion from the import graph in the tests (cool PR though!)

2022-12-02 14:15 UTC, muenzpraeger commented
Well, I should have run _all_ tests. 🤦‍♂️ Dang. Languages like `LaTeX` killed it.

I reverted the functionality only to the first level of embedded languages. That should be mostly sufficient, IMHO.

2022-12-18 16:42 UTC, orta commented
Looks good to me 👍🏻

2022-12-18 16:44 UTC, orta commented
Thanks!

2022-12-18 16:45 UTC, merged