feat: add nunjucks grammar
shikijs/shiki pull request #494
Opened 2023-07-06 19:55 UTC by LM1207

- [x] Add a test if possible
- [x] Format all commit messages with [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I have read docs for [adding a language](https://github.com/shikijs/shiki/blob/main/docs/languages.md#adding-grammar).
- [x] I have searched around and this is the most up-to-date, actively maintained version of the language grammar.
- [x] I have added a sample file that includes a variety of language syntaxes and succinctly captures the idiosyncrasy of a language. See [docs](https://github.com/shikijs/shiki/blob/main/docs/languages.md#adding-grammar) for requirement.

2023-07-14 19:13 UTC, octref commented
Hi – you can't really edit the `languages.ts` manually. Changes will be overwritten.

2023-07-14 19:20 UTC, octref requested changes

2023-07-14 19:20 UTC, octref commented on packages/shiki/src/languages.ts
> +    embeddedLangs: ['css', 'html', 'ini', 'java', 'lua', 'make', 'perl', 'r', 'ruby', 'php', 'sql', 'vb', 'xml', 'xsl', 'yaml', 'bat', 'clojure', 'coffee', 'c', 'cpp', 'diff', 'docker', 'git-commit',
this is dictated by markdown grammar, not nunjucks.

2023-07-14 19:20 UTC, octref commented on packages/shiki/src/languages.ts
> +    embeddedLangs: ['yaml']
this is dependent on the grammar having a `include` rule of `source.yaml` or `text.html`. why are you adding it?

2023-07-15 22:06 UTC, LM1207 commented on packages/shiki/src/languages.ts
> +    embeddedLangs: ['css', 'html', 'ini', 'java', 'lua', 'make', 'perl', 'r', 'ruby', 'php', 'sql', 'vb', 'xml', 'xsl', 'yaml', 'bat', 'clojure', 'coffee', 'c', 'cpp', 'diff', 'docker', 'git-commit',
You have already changed the file, I think I don't need to add the changes again.

2024-01-26 20:45 UTC, antfu commented
Hey, thanks for your contribution! With the [recent rewrite of v1.0](https://github.com/shikijs/shiki/pull/557), we have moved the grammars out of this repository. We generally suggest you [loading the grammar locally](https://shiki.style/guide/load-lang) to move forward. If you believe this is the language that is widely used, you can send an issue or PR to this repo: https://github.com/shikijs/textmate-grammars-themes

Thank you!

2024-01-26 20:45 UTC, closed without merging