Add CodeSandbox interactive demo (with Next.js)
shikijs/shiki pull request #82
Opened 2020-08-26 10:17 UTC by karlhorky

Hi @octref ! 👋

I have been considering different highlighting options (also Prism.js with `react-syntax-highlighter`), and stumbled upon your project through Orta (who used it for the [`shiki-twoslash`](https://www.npmjs.com/package/shiki-twoslash) package for the TypeScript website)

One thing that I was looking for when going through this repo and also the docs website was an interactive demo.

I've set one up on CodeSandbox (with Next.js). It is currently a frozen sandbox (so that I remember to not accidentally make changes to it), but of course happy to have you fork it so that you control the sandbox.

What are your thoughts?

2020-08-26 14:49 UTC, octref commented
> of course happy to have you fork it so that you control the sandbox

Sure, I'll fork and make a sandbox. Thanks for bringing this up. Making it easier for people to fiddle with the API would be great for trying it out and bug reporting.

2020-08-26 14:49 UTC, octref requested changes

2020-08-26 14:49 UTC, octref commented on README.md
> +  Shiki is a beautiful Syntax Highlighter. <a href="http://shiki.matsu.io">Docs</a>. <a href="https://codesandbox.io/s/shiki-next-js-cir0y">CodeSandbox</a>.
I wouldn't want to change this, sorry.

2020-08-26 14:50 UTC, octref commented
@karlhorky It's all good but I'll fork and make a few more necessary changes before merigng. Nothing you need to do on your side. Thanks 👍

2020-08-26 15:53 UTC, karlhorky commented on README.md
> +  Shiki is a beautiful Syntax Highlighter. <a href="http://shiki.matsu.io">Docs</a>. <a href="https://codesandbox.io/s/shiki-next-js-cir0y">CodeSandbox</a>.
All good, just wanted to suggest surfacing it somewhere prominent to save users time.

Other solutions would be good too!

2020-09-02 06:17 UTC, octref commented
I didn't have much success with codesandbox, not sure what's wrong: https://codesandbox.io/s/pmkh0?file=/style.css

![image](https://user-images.githubusercontent.com/4033249/91938646-f600a900-ed26-11ea-8207-80b185b4882c.png)


I can only accept setup like this. I don't want to bring in a lot of dependencies: https://github.com/octref/shiki-starter
If CodeSandbox can do this, I can link to it. Otherwise I'd rather leave a link to the starter template.

2020-09-02 07:48 UTC, karlhorky commented
@octref Yeah I also ran into this - that's why I switched to Next.js, where the dependency resolution seems to work properly.

However, if you want fewer dependencies, looks like it also works just with plain Node.js:

https://codesandbox.io/s/relaxed-haslett-cpuxm?file=/src/index.js

2020-09-03 01:46 UTC, octref commented
CodeSandbox seems really flakey...I can't even move `src/index.js` to `index.js` otherwise it would error out. I cannot change `start` script or `nodemon` devDependency or it would fail:

![image](https://user-images.githubusercontent.com/4033249/92061836-d8d0e680-edc9-11ea-8dfa-8babcd1da6bb.png)

I'm not 100% happy about CSB, but I do agree having a click-to-play option would be nice until something better is available:
https://codesandbox.io/s/shiki-starter-gphup

2020-09-03 01:52 UTC, octref approved these changes

2020-09-03 01:53 UTC, octref commented
Thanks for doing this 🌟

2020-09-03 01:53 UTC, merged

2020-09-03 08:45 UTC, karlhorky commented
> CodeSandbox seems really flakey...I can't even move `src/index.js` to `index.js` otherwise it would crash. I cannot change `start` script or `nodemon` devDependency or it would fail

> I'm not 100% happy about CSB

Ah, you're right, CodeSandbox is not normally this bad, not sure what's up. I've opened two issues about the problems I've seen:

1. https://github.com/codesandbox/codesandbox-client/issues/4806
2. https://github.com/codesandbox/codesandbox-client/issues/4807

---

I've tried repl.it, and it seems to be much more stable:

https://repl.it/@karlhorky/PoliticalPricklyBase#index.js

2020-09-03 08:47 UTC, karlhorky commented
@octref I've tried repl.it, and it seems to be much more stable.

Maybe this is a better option for the demo:

repl.it/@karlhorky/PoliticalPricklyBase#index.js

2020-09-03 13:53 UTC, octref commented
@karlhorky Thanks, I have created https://repl.it/@octref/shiki-starter and linked to it.

2020-09-03 15:45 UTC, karlhorky commented
Awesome, looks great, thanks!

2020-09-03 18:50 UTC, lbogdan commented
Hello, there! Sorry for the poor UX you experienced with CodeSandbox Containers. The way it works is we look for a `start` (or `dev`, `devel`, `serve`) script in `package.json` which we start inside the container, we expect that's a server that listens on one (or more) port(s), and then we expose those ports on `https://id(-port).sse.codesandbox.io`. 

Now, whenever you change the scripts in `packge.json`, you need to restart the sandbox with the "Restart Sandbox" button in the "Server Control Panel" side tab, and we stop the running server and start the new one.

![image](https://user-images.githubusercontent.com/2083930/92152883-19f9e280-ee2c-11ea-9914-b3ecefb66697.png)

I've made a simple starter with `index.js` under the project root here: https://codesandbox.io/s/shiki-starter-gqcfl?file=/index.js .

2020-09-04 00:27 UTC, octref commented
@lbogdan Thanks! I tried refreshing to restart the sandbox. Didn't thought I need to press another button.