Add fallback language support for lazy loading in rehype-shiki
shikijs/shiki pull request #821
Opened 2024-10-29 03:41 UTC by rocklau

…e tests and documentation.

### Description

### Linked Issues

### Additional context

2024-11-03 10:11 UTC, fuma-nama commented on packages/rehype/src/core.ts
> +        if (fallbackLanguage && !(Object.keys(bundledLanguages) as string[]).includes(lang)) {
how about languages that's not included by default, but specified on user land (e.g. custom lang/grammar)?

2024-11-03 10:16 UTC, fuma-nama commented on packages/rehype/src/types.ts
>     * The fallback language to use when specified language is not loaded
I think a more precise description is "fallback language to use when specified language is not loaded or unavailable". With `lazy` enabled, the language will always be loaded, but it might be unavailable (failed to load). and here's where the `fallbackLanguage` is being used.

2024-11-04 03:01 UTC, rocklau commented on packages/rehype/src/core.ts
> +        if (fallbackLanguage && !(Object.keys(bundledLanguages) as string[]).includes(lang)) {
Yeah, For now these situations are not considered. May be check is or not include  LanguageRegistration[]

2024-11-14 03:17 UTC, antfu requested changes

2024-11-14 03:17 UTC, antfu commented on packages/rehype/src/core.ts
> +import { bundledLanguages } from 'shiki'
Core module should not include `bundledLanguages`

2024-11-14 05:25 UTC, fuma-nama commented
I personally think it is not very suitable for `lazy` because the functionality of fallback language was to use another language when specified language of codeblock isn't pre-loaded.

For this to work with `lazy`, you have to watch for error in `loadLanguages`, so `fallbackLanguage` will be used as an error fallback. Given that `loadLanguages` throws error for unknown language, it will work similarly.

2024-11-18 05:33 UTC, closed without merging