Highlighting lines
shikijs/shiki pull request #83
Opened 2020-08-26 22:48 UTC by dceddia

I'm not sure this is ready to merge, but I wanted to put it up to help the discussion in #74.

The broad idea here is to pass an array of line numbers and ranges into Shiki when calling `codeToHtml`, and it will then add appropriate classes to the highlighted/added/deleted/focused lines.

2020-09-02 15:19 UTC, aulneau commented
I have my own fork that supports the ability to parse comments, abd if a line contains a comment that says singularly `highlight`, it will add a class to the line and remove the comment

2020-09-03 02:40 UTC, octref requested changes
Thanks, good work 👍 

Although I'd prefer something like this as the option:

```ts
interface LineOption {
  line: number
  classes?: string[]
  skipTokenization?: boolean // default to false
}

interface HTMLRendererOption {
  lineOptions: LineOption[]
}
```

because:
- I don't think adding string number ranges to the API is useful. That should be handled by markdown plugin libraries.
- I find the class names a bit arbitrary. I'd like to let users pick their own classnames.

2020-09-03 02:40 UTC, octref commented on packages/shiki/src/__tests__/simple.test.ts
> +  expect(out).toBe(
You can use `toMatchSnapshot`.

2020-09-03 02:40 UTC, octref commented on packages/shiki/src/highlighter.ts
> +  debugColors?: boolean
Wondering if this is useful at all. Maybe only add it if someone requests?

2020-09-03 02:40 UTC, octref commented on packages/shiki/src/highlighter.ts
> +  deleteLines?: (string | number)[]
What's the usecase for `deletedLines`?

2020-09-03 18:18 UTC, orta commented on packages/shiki/src/highlighter.ts
> +  deleteLines?: (string | number)[]
I wonder if it's for something like:

```diff
+ before
- after
```

2020-09-04 00:36 UTC, octref commented on packages/shiki/src/highlighter.ts
> +  deleteLines?: (string | number)[]
But wouldn't writing that inline be weird? I'd imagine someone highlight with the `diff` grammar.

2020-09-04 05:01 UTC, dceddia commented on packages/shiki/src/highlighter.ts
> +  debugColors?: boolean
Ah yeah I probably should've split this out as a separate feature/PR. I can do that.

This was very handy to have when I was customizing a color theme though! Before this, I was pretty much grepping through the color theme JSON for hex values and hoping that I was changing the right instance of that color. Having the scope names on the HTML elements made it much easier to track down the right colors to change.

Maybe there are better ways to do that, using some other tool to customize the color scheme. But I wanted to see them in context on the blog with as fast of a feedback loop as I could manage.

2020-09-04 05:11 UTC, dceddia commented on packages/shiki/src/highlighter.ts
> +  deleteLines?: (string | number)[]
Yeah this was pretty much because I wanted a JSX-highlighted diff - check out [this example](https://daveceddia.com/react-confirmation-modal-state-machine/#display-the-error). I wasn't sure if Shiki supported diff combined with other grammars (jsxdiff, diffjsx, jsx+diff, something like that)... does it? I think I tried a few things but couldn't get it working.

From the related issue #74 here's an example of [what my Markdown looks like](https://github.com/shikijs/shiki/issues/74#issuecomment-681168224) for this. I've got comments at the top specifying the lines, and I strip those off at build time so that I can pass line numbers to Shiki. I toyed with the idea of using the diff markers +/- as line prefixes but it was just too painful to write out code that way 😄

2020-09-04 05:26 UTC, dceddia commented
I like your `LineOption` idea a lot! It's much cleaner and more general-purpose 👍 And the `skipTokenization` property will take care of the `deleteLines` case. The name `LineOption` doesn't really give a clue to what it's useful for but I can't really think of a better name.

The add/highlight/delete/focus attributes felt a bit hacky to me too. It started with just the highlightLines, and as it grew, it felt a bit "off" but I couldn't put my finger on it.

I think the `LineOption` would also extend nicely for another thing I wanted to add, the ability to highlight a range of characters within a line (say, for underlining a word or a changed part).

2020-09-10 19:00 UTC, codepunkt commented on packages/shiki/src/renderer.ts
> +    let highlightClasses = ''
I have another PR open (#77). Original idea behind the PR was to wrap every line in a `span` so i could easily add line numbers via CSS counters.

Due to the comments of @octref on that PR, i suggest calling this variable `lineClasses` instead of `highlightClasses` and start with a default class of `line`.

By doing so, we'd always wrap lines in a span, and that span would at least have the "line" class - which would obsolete my PR.

```javascript
let lineClasses = [
  'line',
  highlightedLines.has(lineNo) && 'hl',
  addLines.has(lineNo) && 'add',
  deleteLines.has(lineNo) && 'del',
  focusLines.has(lineNo) && 'foc',
].filter(Boolean).join(' ')

html += `<span class="${lineClasses}">`

if (l.length > 0) {
  l.forEach(token => {
    html += `<span style="color: ${token.color || options.fg}">${escapeHtml(
      token.content
    )}</span>`
  })
}

// Newline goes before the close, so that display:block on the line will work
html += `\n</span>`
```

2020-09-13 07:25 UTC, octref commented on packages/shiki/src/highlighter.ts
> +  debugColors?: boolean
I think it's better to just open an issue first, describe your use case, and we can see if we have a better way to do this or we have to add an option.

2020-09-13 07:43 UTC, octref commented on packages/shiki/src/highlighter.ts
> +  deleteLines?: (string | number)[]
Can we start a separate issue for that feature, and not include it here for now?

I think what you have done is nice, but since highlighting is fast and static asset generation doesn't get rerun a lot, I think it's ok to highlight 2 duplicate files so the deleted lines can also have some color.

For example:

```
console.log(`
+  bar
-  foo
`)
```

We could highlight
```js
console.log(`
  foo
`)
```

and

```js
console.log(`
  bar
`)
```

We can just drop `skipTokenization` for now.

2020-09-13 07:47 UTC, octref commented on packages/shiki/src/renderer.ts
> +    let highlightClasses = ''
> lineClasses instead of highlightClasses and start with a default class of line

👍  for that, but maybe as `LineOption.classes`, see top review comment.

2020-11-10 09:32 UTC, sv3nk commented
Hey everyone,

really excited for the idea of highlighting lines with shiki.
Is this currently being worked on or was something like it already included?

2021-01-10 11:41 UTC, m1guelpf commented
Are there any updates on this?

2021-02-04 15:48 UTC, aarondfrancis commented
Also really looking forward to this!

2021-04-07 03:55 UTC, octref commented
Please rebase and reopen if you still have time to dig into this. Thanks 🙏

2021-04-07 03:55 UTC, closed without merging

2021-11-21 13:26 UTC, mariusschulz commented
@octref, I've submitted PR #259 and implemented a simplified version of this feature that supports highlighting individual lines as well as line ranges. Would love some feedback :)